//: Playground - noun: a place where people can play

import UIKit

var str = "Hello, playground"


//////////////////////////////////CREATION OF CONSTRAINT

///////////////// IMPLEMENTING view1.bottom = view2.bottom - 20
//Here the bottom of view2 (label, button, etc) is 20 points below view1

/*
var myConstraint = NSLayoutConstraint (item: view1,
                   attribute: NSLayoutAttribute.Bottom, 
                    relatedBy: NSLayoutRelation.Equal, 
                    toItem: view2,
                    attribute: NSLayoutAttribute.Bottom, 
                    multiplier: 1.0,
                    constant: -20
                    )
*/

////////////////mybutton = 5 * myLabel
//Expanding the width of a button by 5 time the width of the label
/*
var myConstraint = NSLayoutConstraint (item: mybutton,
                    attribute: NSLayoutAttribute.Width,
                    relatedBy: NSLayoutRelation.Equal,
                    toItem: mylabel,
                    attribute: NSLayoutAttribute.Width,
                    multiplier: 5,
                    constant: 0
                    )
*/

////////////////////////mybutton.width >= 200
/*
var myConstraint = NSLayoutConstraint (item: mybutton,
                                       attribute: NSLayoutAttribute.Width,
                                       relatedBy: NSLayoutRelation.GreaterThanOrEqual,
                                       toItem: nil,
                                       attribute: NSLayoutAttribute.Width,
                                       multiplier: 200,
                                       constant: 0
                                       )
*/

//////////////////////////// ADDING CONSTRAINTS TO A VIEW

//Achieved by passing arguments to the addConstraint method of the view (label,button,etc) to which it is being added. You can add multiple constraints to a view. 
/*
var myConstraint = NSLayoutConstraint (item: mybutton,
                                       attribute: NSLayoutAttribute.Width,
                                       relatedBy: NSLayoutRelation.Equal,
                                       toItem: mylabel,
                                       attribute: NSLayoutAttribute.Width,
                                       multiplier: 50,
                                       constant: 0
                                      )

 //Add constraint to 'view'
self.view.addConstraint(myConstraint)
*/

//////////////////////////// TURNING OFF AUTO RESIZING TRANSLATION
//Turns off autogenerated constraints when you add a subview (eg button) to a superview. There is usually a conflict btw the constraints automatically generated when you pull a view into the superview and the constraints added to the application code

//Create a button
let myButton = UIButton()
//Title of the Button
myButton.setTitle("My Button", forState: UIControlState.Normal)
//Turn off translation
myButton.translatesAutoresizingMaskIntoConstraints = false
//Add to parent view
/*
self.view.addSubview(myButton)
*/

















